// Generated by scripts/generate-embedded-facts.mjs. Do not edit.
export const EMBEDDED_KFD = Object.freeze({
  "package": "@kungfu-tech/kfd",
  "packageVersion": "1.0.0-alpha.42",
  "profileId": "kfd-agent-hub",
  "profileVersion": "0.1.0-alpha.1",
  "manifest": {
    "$schema": "https://kfd.libkungfu.dev/schemas/kfd-agent-hub/manifest.schema.json",
    "schemaVersion": 1,
    "contract": "kfd-agent-hub-profile-manifest",
    "profile": {
      "id": "kfd-agent-hub",
      "version": "0.1.0-alpha.1",
      "status": "alpha",
      "authorityPath": "protocols/agent-hub/README.md"
    },
    "imports": [
      "KFD-1",
      "KFD-2",
      "KFD-3",
      "KFD-7"
    ],
    "topologies": [
      "local-peer",
      "single-vendor-cloud",
      "multi-organization-federation",
      "offline-device"
    ],
    "operations": [
      "capability-advertisement",
      "responsibility-proposal",
      "fact-admission",
      "supersession",
      "completion-assessment",
      "warrant-revocation"
    ],
    "failureCodes": [
      "profile-version-unsupported",
      "profile-root-mismatch",
      "required-feature-unsupported",
      "identity-unresolved",
      "authority-unresolved",
      "authority-expired",
      "authority-revoked",
      "authority-amplification",
      "fact-cut-unavailable",
      "causal-gap",
      "payload-digest-mismatch",
      "idempotency-conflict",
      "conflict-visible",
      "disclosure-insufficient",
      "required-field-withheld",
      "completion-unproved",
      "local-policy-rejected"
    ],
    "surfaces": [
      {
        "id": "profile-authority",
        "path": "protocols/agent-hub/README.md",
        "role": "authority",
        "sha256": "0d9024c9727a9ffb5cdd2912e2f51a5f53a186663be052ef6551095ed19cdaaf"
      },
      {
        "id": "gap-matrix",
        "path": "protocols/agent-hub/gap-matrix.md",
        "role": "analysis",
        "sha256": "3991fceab6c597ed557a7a070ceaa9fa74a2bade65c42e4486bd07b4369c6738"
      },
      {
        "id": "state-machine-guide",
        "path": "protocols/agent-hub/state-machine.md",
        "role": "reference",
        "sha256": "430426ca7618362900e2014e9c977e43ba70c0ed9fb32f691d191f32f1d8bb0c"
      },
      {
        "id": "implementer-guide",
        "path": "protocols/agent-hub/implementer-guide.md",
        "role": "guide",
        "sha256": "95fbb4afbebc9105443dc1254bfac7aad166d61169feaad957780848f2f66b18"
      },
      {
        "id": "reference-state-machine",
        "path": "protocols/agent-hub/reference-state-machine.json",
        "role": "normative",
        "sha256": "0e047020103511fb272d8bc7441a3304c254f160e28952197ef8a32093d1bebf"
      },
      {
        "id": "capabilities-schema",
        "path": "schemas/kfd-agent-hub/capabilities.schema.json",
        "role": "normative",
        "sha256": "d4098d20740cce67156ee1c456dab9fd8454f6e3fb0613810fe1d010f64981cc"
      },
      {
        "id": "exchange-schema",
        "path": "schemas/kfd-agent-hub/exchange.schema.json",
        "role": "normative",
        "sha256": "a43bed367a05fe6ac3d796ec8642dbe2905b92c66438448c35b79d7965bc1a3f"
      },
      {
        "id": "manifest-schema",
        "path": "schemas/kfd-agent-hub/manifest.schema.json",
        "role": "normative",
        "sha256": "79b9c1090ad275f9e3e06dd2170fcacbb7e4ff41873ea705355a6d23e956369f"
      }
    ],
    "governance": {
      "proposal": "https://github.com/kungfu-systems/kfd/issues/new?template=kfd-proposal.yml",
      "counterevidence": "https://github.com/kungfu-systems/kfd/issues/new?template=kfd-counterevidence.yml",
      "pullRequests": "https://github.com/kungfu-systems/kfd/pulls"
    },
    "claimBoundary": "This alpha profile defines a topology-neutral responsibility exchange contract. It is not a numbered KFD, stable certification, evidence of a conforming implementation, external vendor adoption, plural-Hub interoperability, or an industry standard."
  },
  "manifestDigest": "sha256:dab4e93d2a662092eb51e29171dfc8bd0c400daa99899f074e69608b45cc7a59",
  "source": "public-npm-build-input"
});
export const EMBEDDED_ADAPTER_ARTIFACT = Object.freeze({
  "contract": "agent-hub-demo.adapter-artifact/v1",
  "entry": "src/adapter.js",
  "files": [
    {
      "path": "src/adapter.js",
      "sha256": "a78ff48f3ed9b0f826ecbafd306d6661dbcbd065c471db04cd9a020c4262582e"
    },
    {
      "path": "src/artifact.js",
      "sha256": "1c566a90c0d86261156322993845d8fa5e801c6dcaaf3e29def3d8bebab96491"
    },
    {
      "path": "src/canonical.js",
      "sha256": "c25ff39ebbbd1db3498d02271ddef7ae6fb4a85e6668347fe5a58aa949f00d61"
    },
    {
      "path": "src/cas.js",
      "sha256": "2f06bd0ba4fcd92c73b5f33cce404d03b57b961985f6d260cfed98422e264587"
    },
    {
      "path": "src/cli.js",
      "sha256": "cb2782ca7736fb8286c986269771e419f367e2580bace8774ed3b34b308c9778"
    },
    {
      "path": "src/hub.js",
      "sha256": "55b98ee0f6a1151225b6f7923b09a40ad6cbba3447f32abea02b88ad3ca6e3d9"
    },
    {
      "path": "src/product.js",
      "sha256": "13cf2cc2f4514e1ad5ce43fb4726468476e499bd3ad1ac335c1962d6c25ebe61"
    },
    {
      "path": "src/public-kfd.js",
      "sha256": "2ca63785d29627737e5b07be3c7060bfbf1c8c6ca5e522a55f26c2399ff8cf8b"
    },
    {
      "path": "src/scenarios.js",
      "sha256": "5df9ca254303a007171e39910379ca11a45f96d448204d165d061e840ea30788"
    }
  ],
  "root": "sha256:743c297965cff14bad4f430a5cac58b1c9bc76dc33ed165b7e9c52a7be67344b"
});
