name: Artifact Signing Dogfood

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  signing-dogfood:
    permissions:
      actions: read
      contents: read
      issues: write
      id-token: write
      attestations: write
    uses: kungfu-systems/buildchain/.github/workflows/build.yml@v4
    secrets:
      BUILDCHAIN_PROMOTION_TOKEN: ${{ secrets.BUILDCHAIN_PROMOTION_TOKEN }}
