name: Verify

on:
  pull_request:
  push:
    branches:
      - dev/v*/v*
      - alpha/v*/v*
      - release/v*/v*
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    uses: kungfu-systems/buildchain/.github/workflows/check.yml@0a0cb4e40b9d97b1353ee48c77b29dc58049d2fc
    with:
      buildchain-ref: 0a0cb4e40b9d97b1353ee48c77b29dc58049d2fc
      require-version-state: true
      upload-artifacts: true
