name: Verify

on:
  pull_request:
  push:
    branches:
      - dev/v*/v*
      - alpha/v*/v*
      - release/v*/v*
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    uses: kungfu-systems/buildchain/.github/workflows/check.yml@b88097b5e562b4f49cdef3ddee81be6eab5224a2
    with:
      buildchain-ref: b88097b5e562b4f49cdef3ddee81be6eab5224a2
      require-version-state: true
      upload-artifacts: true
