name: Verify

on:
  pull_request:
  push:
    branches:
      - dev/v*/v*
      - alpha/v*/v*
      - release/v*/v*
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    uses: kungfu-systems/buildchain/.github/workflows/check.yml@47bb098a7701e55fcd1276e795acc170574d9744
    with:
      buildchain-ref: 47bb098a7701e55fcd1276e795acc170574d9744
      require-version-state: true
      upload-artifacts: true
